In [3]:
import pandas as pd
import numpy as np

In [4]:
pip install nltk pandas numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import nltk

nltk.download('punkt_tan')
nltk.download('wordnet')

[nltk_data] Error loading punkt_tan: Package 'punkt_tan' not found in
[nltk_data]     index
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

NLTK,
Spacy - NLP Techniques or library


BERT
Transformer
Word Embedding                  "this and above is this Deep Learning."
RNN, LSTM RNN, GRU
Text processing- word2vec, Avgword2vec
Bow,TFIDF,Unigram
Tokenization,Lemmatization

In [6]:
c = """hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python.
sdfsfsfklsdf.sdfsd  ,dsfsdf!  ,dfs  ,sga.=sdf
"""

In [7]:
print(c)

hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python.
sdfsfsfklsdf.sdfsd  ,dsfsdf!  ,dfs  ,sga.=sdf



In [8]:
from nltk.tokenize import sent_tokenize
document = sent_tokenize(c)
document

['hello welcome,I love Python  ,\nI Learn AI/ML  ,also learn Python.',
 'sdfsfsfklsdf.sdfsd  ,dsfsdf!',
 ',dfs  ,sga.=sdf']

In [9]:
for sentence in document:
    print(sentence,"------------")

hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python. ------------
sdfsfsfklsdf.sdfsd  ,dsfsdf! ------------
,dfs  ,sga.=sdf ------------


In [10]:
from nltk.tokenize import word_tokenize
word_tokenize(c)

['hello',
 'welcome',
 ',',
 'I',
 'love',
 'Python',
 ',',
 'I',
 'Learn',
 'AI/ML',
 ',',
 'also',
 'learn',
 'Python',
 '.',
 'sdfsfsfklsdf.sdfsd',
 ',',
 'dsfsdf',
 '!',
 ',',
 'dfs',
 ',',
 'sga.=sdf']

In [11]:
from nltk.tokenize import wordpunct_tokenize

In [12]:
word_token = word_tokenize(c)
word_token

['hello',
 'welcome',
 ',',
 'I',
 'love',
 'Python',
 ',',
 'I',
 'Learn',
 'AI/ML',
 ',',
 'also',
 'learn',
 'Python',
 '.',
 'sdfsfsfklsdf.sdfsd',
 ',',
 'dsfsdf',
 '!',
 ',',
 'dfs',
 ',',
 'sga.=sdf']

In [13]:
from nltk.tokenize import TreebankWordTokenizer,TreebankWordDetokenizer

In [14]:
tokenizer = TreebankWordTokenizer()
dtokenizer = TreebankWordDetokenizer()

In [15]:
corpus = """hello welcome,I love Python  ,
I Learn AI/ML  ,also learn Python.
sdfsfsfklsdf.sdfsd  ,dsfsdf!  ,dfs  ,sga.=sdf
"""
a = tokenizer.tokenize(corpus)
dtokenizer.tokenize(a)

'hello welcome, I love Python, I Learn AI/ML, also learn Python. sdfsfsfklsdf.sdfsd, dsfsdf!, dfs, sga.=sdf'

In [16]:
words = ['Writing','write',"writen",'play','played','playing','run','running','view','cry','cries','finally','finalized']

PorterStemmer

In [17]:
from nltk.stem import PorterStemmer


In [18]:
stemming = PorterStemmer()

In [19]:
for word in words:
    print(f'{word} ---> {stemming.stem(word)}')

Writing ---> write
write ---> write
writen ---> writen
play ---> play
played ---> play
playing ---> play
run ---> run
running ---> run
view ---> view
cry ---> cri
cries ---> cri
finally ---> final
finalized ---> final


In [20]:
stemming.stem('congratulations')

'congratul'

In [21]:
stemming.stem("sitting")

'sit'

Regexpstemmer class

In [22]:
from nltk.stem import RegexpStemmer
reg_stemmer = RegexpStemmer(regexp='ing$|s$|e$|able$|ed$|ies$',min=4)

In [23]:
reg_stemmer.stem('')

''

Snowball Stemmer

In [24]:
from nltk.stem import SnowballStemmer

In [25]:
snowball = SnowballStemmer('english')

In [26]:
for word in words:
    print(f'{word} ====> {snowball.stem(word)}')

Writing ====> write
write ====> write
writen ====> writen
play ====> play
played ====> play
playing ====> play
run ====> run
running ====> run
view ====> view
cry ====> cri
cries ====> cri
finally ====> final
finalized ====> final


Wordnet Lemmatizer

pos-None -n (default)

verb -v 

adjective -a 

adverb -r

In [27]:
from nltk.stem import WordNetLemmatizer

In [28]:
lemmatizer = WordNetLemmatizer()

In [29]:
lemmatizer.lemmatize('playing',pos='v')

KeyboardInterrupt: 

In [ ]:
for word in words:
    print(f'{word} ====> {lemmatizer.lemmatize(word,pos="v")}')

Writing ====> Writing
write ====> write
writen ====> writen
play ====> play
played ====> play
playing ====> play
run ====> run
running ====> run
view ====> view
cry ====> cry
cries ====> cry
finally ====> finally
finalized ====> finalize


In [ ]:
print(lemmatizer.lemmatize('worse',pos='a'),
lemmatizer.lemmatize('better',pos='a'),
lemmatizer.lemmatize('best',pos='a'),
lemmatizer.lemmatize('good',pos='a'),
lemmatizer.lemmatize('better',pos='a'),
lemmatizer.lemmatize('best',pos='a'))


bad good best good good best


In [ ]:
lemmatizer.lemmatize('loudly',pos='r')

'loudly'

In [ ]:
lemmatizer.lemmatize('Fortunately',pos='r')

'Fortunately'

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
print(stopwords.words('german'))
print(stopwords.words('english'))
print(stopwords.words('french'))
print(stopwords.words('spanish'))
print(stopwords.words('portuguese'))
print(stopwords.words('arabic'))
print(stopwords.words('russian'))
print(stopwords.words('italian'))
print(stopwords.words('dutch'))
print(stopwords.words('swedish'))
print(stopwords.words('turkish'))
print(stopwords.words('chinese'))


['aber', 'alle', 'allem', 'allen', 'aller', 'alles', 'als', 'also', 'am', 'an', 'ander', 'andere', 'anderem', 'anderen', 'anderer', 'anderes', 'anderm', 'andern', 'anderr', 'anders', 'auch', 'auf', 'aus', 'bei', 'bin', 'bis', 'bist', 'da', 'damit', 'dann', 'der', 'den', 'des', 'dem', 'die', 'das', 'dass', 'daß', 'derselbe', 'derselben', 'denselben', 'desselben', 'demselben', 'dieselbe', 'dieselben', 'dasselbe', 'dazu', 'dein', 'deine', 'deinem', 'deinen', 'deiner', 'deines', 'denn', 'derer', 'dessen', 'dich', 'dir', 'du', 'dies', 'diese', 'diesem', 'diesen', 'dieser', 'dieses', 'doch', 'dort', 'durch', 'ein', 'eine', 'einem', 'einen', 'einer', 'eines', 'einig', 'einige', 'einigem', 'einigen', 'einiger', 'einiges', 'einmal', 'er', 'ihn', 'ihm', 'es', 'etwas', 'euer', 'eure', 'eurem', 'euren', 'eurer', 'eures', 'für', 'gegen', 'gewesen', 'hab', 'habe', 'haben', 'hat', 'hatte', 'hatten', 'hier', 'hin', 'hinter', 'ich', 'mich', 'mir', 'ihr', 'ihre', 'ihrem', 'ihren', 'ihrer', 'ihres', 'euc

In [ ]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [ ]:
stemmer = PorterStemmer()

In [ ]:
s = nltk.sent_tokenize(c)

In [ ]:
type(s)

list

In [ ]:
for i in range(len(s)):
    w = nltk.word_tokenize(s[i])
    words_not_instopwords = [stemmer.stem(word) for word in w if word not in set(stopwords.words('english'))]
    s[i] = ' '.join(words_not_instopwords)

In [ ]:
for i in s:
    print(i)

hello welcom , i love python , i learn ai/ml , also learn python .
sdfsfsfklsdf.sdfsd , dsfsdf !
, df , sga.=sdf


In [ ]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer('english')

for i in range(len(s)):
    W = nltk.word_tokenize(s[i])
    words_not_instopwords = [stemmer.stem(word) for word in W if word not in set(stopwords.words('english'))]
    s[i] = ' '.join(words_not_instopwords)

In [ ]:
for i in s:
    print(i)

hello welcom , love python , learn ai/ml , also learn python .
sdfsfsfklsdf.sdfsd , dsfsdf !
, df , sga.=sdf


In [ ]:
from nltk.stem import WordNetLemmatizer
lammatizer = WordNetLemmatizer()

for i in range(len(s)):
    W = nltk.word_tokenize(s[i])
    words_not_instopwords = [lammatizer.lemmatize(word.lower(),pos='v') for word in W if word not in set(stopwords.words('english'))]
    s[i] = ' '.join(words_not_instopwords)

In [ ]:
for i in s:
    print(i)

hello welcom , love python , learn ai/ml , also learn python .
sdfsfsfklsdf.sdfsd , dsfsdf !
, df , sga.=sdf


In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
    for i in range(len(s)):
        W = nltk.word_tokenize(s[i])
        words_not_instopwords = [word for word in W if word not in set(stopwords.words('english'))]
        pos_tags = nltk.pos_tag(words_not_instopwords)
        print(pos_tags)


[('hello', 'NN'), ('welcom', 'NN'), (',', ','), ('love', 'VB'), ('python', 'NN'), (',', ','), ('learn', 'JJ'), ('ai/ml', 'NN'), (',', ','), ('also', 'RB'), ('learn', 'JJ'), ('python', 'NN'), ('.', '.')]
[('sdfsfsfklsdf.sdfsd', 'NN'), (',', ','), ('dsfsdf', 'NN'), ('!', '.')]
[(',', ','), ('df', 'NN'), (',', ','), ('sga.=sdf', 'NN')]


In [ ]:
nltk.pos_tag(['Python', 'is', 'a', 'programming', 'language'])

[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('programming', 'JJ'),
 ('language', 'NN')]

In [ ]:
nltk.pos_tag_sents([nltk.word_tokenize("Taj Mahal is a beautiful Monument in India.")])

[[('Taj', 'NNP'),
  ('Mahal', 'NNP'),
  ('is', 'VBZ'),
  ('a', 'DT'),
  ('beautiful', 'JJ'),
  ('Monument', 'NN'),
  ('in', 'IN'),
  ('India', 'NNP'),
  ('.', '.')]]

In [ ]:
for i in "Taj Mahal is a beautiful Monument in India.".split():
    print(i, "===>", nltk.pos_tag([i]))


Taj ===> [('Taj', 'NN')]
Mahal ===> [('Mahal', 'NN')]
is ===> [('is', 'VBZ')]
a ===> [('a', 'DT')]
beautiful ===> [('beautiful', 'NN')]
Monument ===> [('Monument', 'NN')]
in ===> [('in', 'IN')]
India. ===> [('India.', 'NN')]


Named Entity Recognition

In [ ]:
import nltk
sentence = nltk.word_tokenize("Taj Mahal is a beautiful Monument in India.")
sentence

['Taj', 'Mahal', 'is', 'a', 'beautiful', 'Monument', 'in', 'India', '.']

In [ ]:
w = nltk.pos_tag(sentence)
w

[('Taj', 'NNP'),
 ('Mahal', 'NNP'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('beautiful', 'JJ'),
 ('Monument', 'NN'),
 ('in', 'IN'),
 ('India', 'NNP'),
 ('.', '.')]

In [ ]:
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!


True

In [ ]:
try:
    nltk.ne_chunk(w).draw()
except Exception as e:
    print(e)


Sentiment Analysis

One hot encoding

Word2Vec Practice

In [ ]:
!pip install gensim

In [ ]:
import gensim
from gensim.models import Word2Vec,keyedvectors

In [ ]:
import gensim.downloader as api

In [ ]:
model = api.load("word2vec-google-news- ")

ValueError: Incorrect model/corpus name

In [ ]:
model['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
model.most_similar('ball')

[('balls', 0.6992624402046204),
 ('upfield', 0.6896207332611084),
 ('downfield', 0.639072835445404),
 ('dribbler', 0.6218728423118591),
 ('balll', 0.6199931502342224),
 ('dribble', 0.616877555847168),
 ('ball_squirted', 0.6110138297080994),
 ('leftfooted', 0.6020259261131287),
 ('puck', 0.5981723666191101),
 ('mishit', 0.5948783159255981)]

In [ ]:

model.similarity('bottle','man')

0.18008712

In [ ]:
a = model['king'] - model['man'] + model['woman']

In [ ]:
a

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [ ]:
model.most_similar([a])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

Tokenization Practice

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords


In [ ]:
corpus = """hello welcome, to Rudra's AI/ML course. I love Python and I am learning AI/ML."""

In [ ]:
sent_tokenize(corpus)

["hello welcome, to Rudra's AI/ML course.",
 'I love Python and I am learning AI/ML.']

In [ ]:
word_tokenize(corpus)

['hello',
 'welcome',
 ',',
 'to',
 'Rudra',
 "'s",
 'AI/ML',
 'course',
 '.',
 'I',
 'love',
 'Python',
 'and',
 'I',
 'am',
 'learning',
 'AI/ML',
 '.']

In [ ]:
from nltk.tokenize import wordpunct_tokenize

In [ ]:
wordpunct_tokenize(corpus)

['hello',
 'welcome',
 ',',
 'to',
 'Rudra',
 "'",
 's',
 'AI',
 '/',
 'ML',
 'course',
 '.',
 'I',
 'love',
 'Python',
 'and',
 'I',
 'am',
 'learning',
 'AI',
 '/',
 'ML',
 '.']

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
stmmer = PorterStemmer()
a = nltk.sent_tokenize(corpus)

In [ ]:
for i in range(len(a)):
    w = nltk.word_tokenize(a[i])
    words_not_instopwords = [stmmer.stem(word) for word in w if word not in set(stopwords.words('english'))]
    a[i] = ' '.join(words_not_instopwords)

In [ ]:
a

["hello welcom , rudra 's ai/ml cours .", 'i love python i learn ai/ml .']

Bag of Words Practicals(BOW)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('spam_messages_1000.csv')

In [ ]:
df

,label,message
0,spam,Claim your free vacation package now. Limited ...
1,ham,Meeting rescheduled to 3 PM.
2,ham,Are you coming to the party tonight?
3,spam,Claim your free vacation package now. Limited ...
4,ham,Can you call me back when you're free?
...,...,...
995,spam,You have been selected for a cash prize. Reply...
996,ham,Don't forget to bring the documents for the me...
997,ham,Thanks for your help earlier!
998,ham,"Don't worry, everything will be fine."


In [ ]:
import re
import nltk
nltk.download('punkt')
ps = PorterStemmer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
corpus=[]
for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z]',' ',df['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
print(corpus)
print(len(corpus))

['claim free vacat packag limit time offer', 'meet reschedul pm', 'come parti tonight', 'claim free vacat packag limit time offer', 'call back free', 'meet reschedul pm', 'happi birthday hope great day', 'subscript end renew avoid interrupt', 'meet reschedul pm', 'scam realli', 'get cheap med onlin without prescript visit site', 'urgent account compromis click link secur', 'thank help earlier', 'let catch coffe sometim', 'let catch coffe sometim', 'pre approv loan appli', 'forget bring document meet', 'worri everyth fine', 'thank help earlier', 'worri everyth fine', 'urgent account compromis click link secur', 'scam realli', 'forget bring document meet', 'hey still lunch today', 'let catch coffe sometim', 'subscript end renew avoid interrupt', 'claim free vacat packag limit time offer', 'call back free', 'claim free vacat packag limit time offer', 'late traffic realli bad right', 'urgent account compromis click link secur', 'subscript end renew avoid interrupt', 'thank help earlier', '

In [ ]:
##create the Bag of wores model
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv= CountVectorizer(max_features=1000,lowercase=True)
X = cv.fit_transform(corpus).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
cv= CountVectorizer(max_features=1000,lowercase=True,binary=True)
X = cv.fit_transform(corpus).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
X.shape

(1000, 83)

TF-IDF

In [ ]:
df

,label,message
0,spam,Claim your free vacation package now. Limited ...
1,ham,Meeting rescheduled to 3 PM.
2,ham,Are you coming to the party tonight?
3,spam,Claim your free vacation package now. Limited ...
4,ham,Can you call me back when you're free?
...,...,...
995,spam,You have been selected for a cash prize. Reply...
996,ham,Don't forget to bring the documents for the me...
997,ham,Thanks for your help earlier!
998,ham,"Don't worry, everything will be fine."


In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
wordlemma = WordNetLemmatizer()

In [ ]:
corpus=[]
for i in range(0,len(df)):
    review = re.sub('[^a-zA-Z]',' ',df['message'][i])
    review = review.lower()
    review = review.split()
    review = [wordlemma.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['claim free vacation package limited time offer',
 'meeting rescheduled pm',
 'coming party tonight',
 'claim free vacation package limited time offer',
 'call back free',
 'meeting rescheduled pm',
 'happy birthday hope great day',
 'subscription ending renew avoid interruption',
 'meeting rescheduled pm',
 'scam really',
 'get cheap med online without prescription visit site',
 'urgent account compromised click link secure',
 'thanks help earlier',
 'let catch coffee sometime',
 'let catch coffee sometime',
 'pre approved loan apply',
 'forget bring document meeting',
 'worry everything fine',
 'thanks help earlier',
 'worry everything fine',
 'urgent account compromised click link secure',
 'scam really',
 'forget bring document meeting',
 'hey still lunch today',
 'let catch coffee sometime',
 'subscription ending renew avoid interruption',
 'claim free vacation package limited time offer',
 'call back free',
 'claim free vacation package limited time offer',
 'late traffic really

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=1000)

In [ ]:
X = tfidf.fit_transform(corpus).toarray()

In [ ]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.57735027],
       [0.        , 0.53274258, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
tfidf = TfidfVectorizer(max_features=1000,ngram_range=(2,2))

In [ ]:
X = tfidf.fit_transform(corpus).toarray()

In [ ]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.70710678],
       [0.        , 0.57735027, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
tfidf.vocabulary_

{'claim free': 13,
 'free vacation': 28,
 'vacation package': 64,
 'package limited': 46,
 'limited time': 39,
 'time offer': 61,
 'meeting rescheduled': 44,
 'rescheduled pm': 55,
 'coming party': 17,
 'party tonight': 47,
 'call back': 8,
 'back free': 4,
 'happy birthday': 32,
 'birthday hope': 6,
 'hope great': 36,
 'great day': 31,
 'subscription ending': 59,
 'ending renew': 23,
 'renew avoid': 53,
 'avoid interruption': 3,
 'scam really': 56,
 'get cheap': 29,
 'cheap med': 12,
 'med online': 43,
 'online without': 45,
 'without prescription': 68,
 'prescription visit': 49,
 'visit site': 65,
 'urgent account': 63,
 'account compromised': 0,
 'compromised click': 18,
 'click link': 15,
 'link secure': 40,
 'thanks help': 60,
 'help earlier': 33,
 'let catch': 38,
 'catch coffee': 11,
 'coffee sometime': 16,
 'pre approved': 48,
 'approved loan': 2,
 'loan apply': 41,
 'forget bring': 26,
 'bring document': 7,
 'document meeting': 21,
 'worry everything': 70,
 'everything fine': 

Spam_messages_Detaction_Task

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('spam_messages_1000.csv',encoding='latin-1')

In [ ]:
df

,label,message
0,spam,Claim your free vacation package now. Limited ...
1,ham,Meeting rescheduled to 3 PM.
2,ham,Are you coming to the party tonight?
3,spam,Claim your free vacation package now. Limited ...
4,ham,Can you call me back when you're free?
...,...,...
995,spam,You have been selected for a cash prize. Reply...
996,ham,Don't forget to bring the documents for the me...
997,ham,Thanks for your help earlier!
998,ham,"Don't worry, everything will be fine."


In [33]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer,RegexpStemmer,SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df.columns = ['label','message']

In [ ]:
df.head

<bound method NDFrame.head of     label                                            message
0    spam  Claim your free vacation package now. Limited ...
1     ham                       Meeting rescheduled to 3 PM.
2     ham               Are you coming to the party tonight?
3    spam  Claim your free vacation package now. Limited ...
4     ham             Can you call me back when you're free?
..    ...                                                ...
995  spam  You have been selected for a cash prize. Reply...
996   ham  Don't forget to bring the documents for the me...
997   ham                      Thanks for your help earlier!
998   ham              Don't worry, everything will be fine.
999  spam               Act now to receive your free iPhone!

[1000 rows x 2 columns]>

In [ ]:
df.head()

,label,message
0,spam,Claim your free vacation package now. Limited ...
1,ham,Meeting rescheduled to 3 PM.
2,ham,Are you coming to the party tonight?
3,spam,Claim your free vacation package now. Limited ...
4,ham,Can you call me back when you're free?


In [ ]:
df['label'].value_counts()

label
ham     512
spam    488
Name: count, dtype: int64

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r"\d+","",text)
    text = [lemmatizer.lemmatize(word) for word in text.split() if word not in stop_words and word not in string.punctuation]
    text = ' '.join(text)
    return text

df['cleaned_message'] = df['message'].apply(clean_text)
df[['message', 'cleaned_message']]


,message,cleaned_message
0,Claim your free vacation package now. Limited ...,claim free vacation package now. limited time ...
1,Meeting rescheduled to 3 PM.,meeting rescheduled pm.
2,Are you coming to the party tonight?,coming party tonight?
3,Claim your free vacation package now. Limited ...,claim free vacation package now. limited time ...
4,Can you call me back when you're free?,call back free?
...,...,...
995,You have been selected for a cash prize. Reply...,selected cash prize. reply win claim.
996,Don't forget to bring the documents for the me...,forget bring document meeting.
997,Thanks for your help earlier!,thanks help earlier!
998,"Don't worry, everything will be fine.","worry, everything fine."


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['label_num'] = le.fit_transform(df['label'])


In [ ]:
df

,label,message,cleaned_message,label_num
0,spam,Claim your free vacation package now. Limited ...,claim free vacation package now. limited time ...,1
1,ham,Meeting rescheduled to 3 PM.,meeting rescheduled pm.,0
2,ham,Are you coming to the party tonight?,coming party tonight?,0
3,spam,Claim your free vacation package now. Limited ...,claim free vacation package now. limited time ...,1
4,ham,Can you call me back when you're free?,call back free?,0
...,...,...,...,...
995,spam,You have been selected for a cash prize. Reply...,selected cash prize. reply win claim.,1
996,ham,Don't forget to bring the documents for the me...,forget bring document meeting.,0
997,ham,Thanks for your help earlier!,thanks help earlier!,0
998,ham,"Don't worry, everything will be fine.","worry, everything fine.",0


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100,ngram_range=(2,3))
X = tfidf.fit_transform(df['cleaned_message']).toarray()

In [ ]:
X

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.4472136, ..., 0.       , 0.       ,
        0.       ]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
Y = df['label_num']
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state=40)

In [ ]:
x_train

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.25819889, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
model = MultinomialNB()
model.fit(x_train,y_train)
y_pred = model.predict(x_text)
y_pred

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1])

In [ ]:
accuracy_score(y_test,y_pred)

0.91

In [ ]:
confusion_matrix(y_test,y_pred)

array([[103,   0],
       [ 18,  79]], dtype=int64)

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92       103
           1       1.00      0.81      0.90        97

    accuracy                           0.91       200
   macro avg       0.93      0.91      0.91       200
weighted avg       0.92      0.91      0.91       200



In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier


In [ ]:
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [ ]:
print(logreg.score(x_test,y_test))

0.91


In [ ]:
# def predict_message(msg):
#     cleaned = clean_text(msg)
#     vector = tfidf.transform([cleaned])
#     print(vector)
#     pred_ans = model.predict(vector)
#     return 'Spam' if pred_ans[0] == 1 else 'Ham'


# predict_message("hello world")

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

# Step 1: Preprocessing already done
X = df['cleaned_message']
y = df['label_num']

# Step 2: Fit vectorizer on all training data
tfidf = TfidfVectorizer(max_features=100)
X_tfidf = tfidf.fit_transform(X)

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

# Step 4: Train the model
model = MultinomialNB()
model.fit(X_train, y_train)


,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [ ]:
def predict_message(msg):
    cleaned = clean_text(msg)
    vector = tfidf.transform([cleaned])  
    print(vector)
    pred_ans = model.predict(vector)
    return 'Spam' if pred_ans == 1 else 'Ham'

predict_message("WIN CASE")


  (0, 81)	1.0


'Spam'

In [30]:
df = pd.read_csv('IMDB Dataset.csv')
df

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive
...,...,...
49995,I thought this movie did a down right good job...,positive
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative
49997,I am a Catholic taught in parochial elementary...,negative
49998,I'm going to have to disagree with the previou...,negative


In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [31]:
## Clearn Data
from bs4 import BeautifulSoup
from textblob import TextBlob

def remove_html(text):
    return BeautifulSoup(text,"html.parser").get_text()

def remove_emojis(text):
    return text.encode('ascii','ignore').decode('ascii')

def correct_spelling(text):
    return str(TextBlob(text).correct())

In [ ]:
pip install bs4 textblob

  Using cached beautifulsoup4-4.13.4-py3-none-any.whl.metadata (3.8 kB)
  Using cached soupsieve-2.7-py3-none-any.whl.metadata (4.6 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   ---------------------------------------- 624.3/624.3 kB 5.8 MB/s eta 0:00:00
Using cached beautifulsoup4-4.13.4-py3-none-any.whl (187 kB)
Using cached soupsieve-2.7-py3-none-any.whl (36 kB)

   ---------- ----------------------------- 1/4 [beautifulsoup4]
   ---------- ----------------------------- 1/4 [beautifulsoup4]
   ---------- ----------------------------- 1/4 [beautifulsoup4]
   ---------- ----------------------------- 1/4 [beautifulsoup4]
   -------------------- ------------------- 2/4 [textblob]
   -------------------- ------------------- 2/4 [textblob]
   -------------------- ------------------- 2/4 [textblob]
   ---------------------------------------- 4/4 [bs4]

Note: you may need to restart the kernel to use updated packages.


In [34]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
reviews = []
def clearn_text(text):
    text = text.lower()
    text = re.sub(r'\d+',"",text)
    text = [lemmatizer.lemmatize(word) for word in text.split() if word not in stop_words and word not in string.punctuation]
    text = ' '.join(text)
    return text

df['clearn_review'] = df['review'].apply(clearn_text)



In [35]:

df['clearn_review'] = df['clearn_review'].apply(remove_html)
df['clearn_review'] = df['clearn_review'].apply(remove_emojis)


In [ ]:
# pip install cleantext

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# from cleantext import clean

# def clean_using_lib(text):
#     return clean(text)
                
# df['clearn_review'] = df['clearn_review'].apply(clean_using_lib)


In [36]:
df

,review,sentiment,clearn_review
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode hoo...
1,A wonderful little production. <br /><br />The...,positive,wonderful little production. the filming techn...
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,negative,basically there's family little boy (jake) thi...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"petter mattei's ""love time money"" visually stu..."
...,...,...,...
49995,I thought this movie did a down right good job...,positive,thought movie right good job. creative origina...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,"bad plot, bad dialogue, bad acting, idiotic di..."
49997,I am a Catholic taught in parochial elementary...,negative,catholic taught parochial elementary school nu...
49998,I'm going to have to disagree with the previou...,negative,going disagree previous comment side maltin on...


In [61]:
tfidf = TfidfVectorizer(max_features = 1702,ngram_range=(2,3))
X = tfidf.fit_transform(df['clearn_review']).toarray()

In [62]:
print(X.shape)

(50000, 1702)


In [63]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['sentiment_num'] = label_encoder.fit_transform(df['sentiment'])  


In [64]:
df

,review,sentiment,clearn_review,sentiment_num
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode hoo...,1
1,A wonderful little production. <br /><br />The...,positive,wonderful little production. the filming techn...,1
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...,1
3,Basically there's a family where a little boy ...,negative,basically there's family little boy (jake) thi...,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"petter mattei's ""love time money"" visually stu...",1
...,...,...,...,...
49995,I thought this movie did a down right good job...,positive,thought movie right good job. creative origina...,1
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,"bad plot, bad dialogue, bad acting, idiotic di...",0
49997,I am a Catholic taught in parochial elementary...,negative,catholic taught parochial elementary school nu...,0
49998,I'm going to have to disagree with the previou...,negative,going disagree previous comment side maltin on...,0


In [65]:
df.sample(10)

,review,sentiment,clearn_review,sentiment_num
30940,So we compromised. This was a fairly charming ...,positive,"compromised. fairly charming film, liked art d...",1
37618,Holy @#%& this movie was still warm and juicy ...,negative,holy @#%& movie still warm juicy pile made wit...,0
34051,This is the first time I ever saw a movie with...,negative,"first time ever saw movie jamie foxx, bet last...",0
14592,First i will say that i am going to be as subj...,negative,first say going subjective can.there potential...,0
47108,"I, like so many others on here, bought this mo...",negative,"i, like many others here, bought movie local w...",0
17367,"Though the story is essentially routine, and t...",positive,"though story essentially routine, ""surprise"" e...",1
21574,"The Honey, I Shrunk the Kids franchise was a h...",negative,"honey, shrunk kid franchise huge deal mention ...",0
32058,"Although the acting was excellent, I spent the...",negative,"although acting excellent, spent whole movie w...",0
44790,Murders are occurring in a Texas desert town. ...,negative,murder occurring texas desert town. responsibl...,0
4950,Joe D'Amato might have made some other notable...,negative,joe d'amato might made notable movie long prol...,0


In [66]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
x_train,x_test,y_train,y_test = train_test_split(X,df['sentiment_num'],test_size=0.1,random_state=50)

In [67]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
model = MultinomialNB()

In [69]:
model.fit(x_train,y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [70]:
y_pred = model.predict(x_test)

In [71]:
y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [72]:
accuracy_score(y_test,y_pred)

0.7754

In [73]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.75      0.77      2507
           1       0.76      0.80      0.78      2493

    accuracy                           0.78      5000
   macro avg       0.78      0.78      0.78      5000
weighted avg       0.78      0.78      0.78      5000



In [74]:
confusion_matrix(y_test,y_pred)

array([[1873,  634],
       [ 489, 2004]], dtype=int64)

In [75]:
from nltk.tokenize import word_tokenize
maxi = 0
for i in df['clearn_review']:
    j = word_tokenize(i)
    if(len(j) > maxi):
        maxi = len(j)
print(maxi)


1702
